features = ["trip_distance","driver_gps_accuracy","driver_distance","is_peak_hour","week","driver_cluster_label","customer_cluster_label","historical_completed_bookings"]

target = "is_completed"
test_size = 0.2

[xgboost]
n_estimators = 300
max_depth = 6
learning_rate = 0.1
subsample = 0.8
colsample_bytree = 0.8
min_child_weight = 1
random_state = 42
tree_method = "hist"
scale_pos_weight = 1.2
eval_metric="aucpr"
reg_alpha = 0.2
reg_lambda = 2

[gridsearch]
enable = true
scoring = "f1"
cv = 3
n_jobs = 6
verbose = 1


[param_grid]
n_estimators = [100, 200]
max_depth = [6, 10]
learning_rate = [0.01, 0.1]
subsample = [0.6, 0.8, 1.0]
colsample_bytree = [0.6, 0.8, 1.0]
min_child_weight = [1, 3, 5]
gamma = [0, 1]


